const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class TelegramView {
  constructor({request,render,toast,openModal,unauthorized}) {Object.assign(this,{request,render,toast,openModal,unauthorized});this.active=true;this.click=e=>this.onClick(e);document.addEventListener('click',this.click);}
  destroy(){this.active=false;document.removeEventListener('click',this.click);this.data=null;this.url=null;}
  async load(){if(!this.active||this.loading)return;this.loading=true;try{const d=await this.request('/telegram');if(this.active){this.data=d;this.error='';if(d.linked)this.url=null;}}catch(e){if(this.active){this.error=e.status===503?'Le raccordement Telegram est en préparation.':e.message;if([401,403].includes(e.status))this.unauthorized(e);}}finally{this.loading=false;if(this.active)this.render();}}
  card(){
    const d=this.data,off=this.busy?'disabled':'',button=(id,label)=>`<button class="btn" data-telegram="${id}" ${off}>${label}</button>`;
    const quiet=d?.quietUntil>Date.now(),statuses={accepted:'Accepté par Telegram (lecture non vérifiée)',unknown:'Envoi non confirmé : vérifiez Telegram, aucun renvoi automatique.',rejected:'Envoi refusé par Telegram. Vérifiez le bot ou reliez votre compte.',retry:'Telegram demande de patienter avant une nouvelle tentative.'};
    return `<section class="card card-pad telegram-settings"><h2>Vos rappels Telegram</h2><p>Résumé à 7 h · Rendez-vous sans heure à 9 h · Rendez-vous datés une heure avant. Heure de Paris.</p>${this.error?`<p role="alert">${esc(this.error)}</p>`:''}${!d?'':`<p>${d.linked?(d.enabled&&!quiet?'Votre Telegram est relié. Rappels activés.':'Votre Telegram est relié. Rappels suspendus.'):'Reliez votre conversation privée avec le bot Maison.'}</p>${!d.workerHealthy?'<p role="alert">Le service de rappels reste à vérifier.</p>':d.linked&&!d.calendarHealthy?'<p role="alert">Lecture de l’agenda non confirmée.</p>':''}${quiet?'<p>Journée tranquille : vos rappels sont suspendus jusqu’à demain à 7 h.</p>':''}<div class="row wrap">${d.linked?button(d.enabled?'disable':'enable',d.enabled?'Suspendre mes rappels':'Activer mes rappels')+button(quiet?'resume':'quiet',quiet?'Reprendre maintenant':'Journée tranquille')+(d.enabled&&!quiet?button('test','Tester la réception'):'')+button('unlink','Dissocier Telegram'):button('link','Relier mon Telegram')}</div>${this.url?`<p><a class="btn primary" href="${esc(this.url)}" target="_blank" rel="noopener noreferrer">Ouvrir Telegram et démarrer Maison</a></p><p class="form-note">Lien personnel valable dix minutes. Appuyez sur Démarrer dans Telegram, puis revenez ici et actualisez.</p>`:''}${d.lastDelivery?`<p class="form-note">Dernier envoi : ${esc(statuses[d.lastDelivery.status]??'À vérifier')}</p>`:''}`}${button('refresh','Actualiser Telegram')}<p class="form-note">Ces réglages concernent uniquement votre compte. La commande /stop dans le bot dissocie votre Telegram.</p></section>`;
  }
  async onClick(e){const b=e.target.closest('[data-telegram]');if(!b||b.disabled||this.busy||!this.active)return;const a=b.dataset.telegram;if(a==='refresh')return this.load();
    if(a==='unlink'){this.openModal('Dissocier Telegram ?',`<p>Vos rappels s’arrêtent. L’autre compte conserve ses réglages.</p><div class="form-footer"><button class="btn" data-action="close">Retour</button><button class="btn primary" data-telegram="confirm-unlink">Dissocier mon compte</button></div>`);return;}
    this.busy=true;this.render();try{
      if(a==='link'){const result=await this.request('/telegram/link',{method:'POST',body:{}});if(this.active)this.url=result.url;}
      else if(a==='test'){this.testKey??=crypto.randomUUID();await this.request('/telegram/test',{method:'POST',body:{},key:this.testKey});this.testKey=null;if(this.active)this.toast('Message de test demandé. Regardez votre Telegram.');}
      else {await this.request('/telegram/settings',{method:'POST',body:{action:a==='confirm-unlink'?'unlink':a}});document.querySelector('#modal').close();}
      if(this.active)await this.load();
    }catch(e){if(this.active)this.error=e.message;}finally{this.busy=false;if(this.active)this.render();}
  }
}
