import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {migrate} from '../scripts/migrate.js';
import {bootstrapFamily} from '../scripts/bootstrap-family.js';
import {TelegramStore} from '../src/services/telegram-store.js';
import {fixture,link} from './telegram-fixtures.js';
import {family,alice,bob} from './fixtures.js';
test('Telegram PostgreSQL pairing, restart, locks, receipt-before-send and membership revocation',{skip:!process.env.TEST_DATABASE_URL},async t=>{
  const admin=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await admin.connect();
  const schema='test_tg_'+randomUUID().replaceAll('-','');await admin.query('create schema '+schema);
  const url=new URL(process.env.TEST_DATABASE_URL);url.searchParams.set('options','-c search_path='+schema+',public');
  const pool=new pg.Pool({connectionString:url.href});t.after(async()=>{await pool.end();await admin.query('drop schema '+schema+' cascade');await admin.end();});
  await migrate(url.href);await migrate(url.href);await bootstrapFamily({databaseUrl:url.href,familyId:family,familyName:'Fictitious',userIds:[alice,bob]});
  const one=fixture(new TelegramStore(pool)),two=fixture(new TelegramStore(pool));await link(one.service,alice,11);await link(one.service,bob,22,2);
  assert.equal((await two.service.status(alice)).linked,true);
  let calls=0;const sender=async()=>{calls++;return calls;};one.client.send=sender;two.client.send=sender;
  await Promise.all([one.service.tick(),two.service.tick()]);assert.equal(calls,2);
  await two.service.tick();assert.equal(calls,2);
  let begun;const sending=new Promise(r=>{begun=r;});let finish;const finishSending=new Promise(r=>{finish=r;});
  one.client.send=async()=>{begun();await finishSending;throw Error('response lost');};
  const pending=one.service.deliver(alice,'ambiguous','Test');await sending;
  await two.service.deliver(alice,'ambiguous','Test');assert.equal(calls,2);finish();await pending;
  await two.service.deliver(alice,'ambiguous','Test');assert.equal(calls,2);
  await pool.query('delete from family_members where family_id=$1 and user_id=$2',[family,alice]);
  await two.service.deliver(alice,'after-revocation','Must not send');assert.equal(calls,2);
  await assert.rejects(two.service.pair(alice));
  const data=(await pool.query('select data from telegram_state')).rows[0].data;
  assert.ok(!JSON.stringify(data).includes('Must not send'));
});
