location = /integrations/alexa {
  limit_except POST { deny all; }
  set $family_alexa http://alexa:3001;
  proxy_pass $family_alexa;
  proxy_set_header Host $host;
  proxy_connect_timeout 2s;
  proxy_read_timeout 8s;
  proxy_next_upstream off;
}
location /integrations/ { return 404; }
